name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build-and-deploy]
  workflow_dispatch:

env:
  PAGE: travel-insurance-a1
  BASE: pujux/landing-pages-11ty-poc-base
  ELEVENTY_IMAGE: puf17640/11ty-poc:latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ env.BASE }}

      - name: Install dependencies
        working-directory: ./${{ env.PAGE}}
        run: npm ci

      - name: Build static site
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.ELEVENTY_IMAGE }}
          options: -v /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ env.PAGE }}:/app
          run: eleventy --output=/app/_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./${{ env.PAGE }}/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
